# Generated by Django 5.0.6 on 2024-06-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retweet',
            name='feeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feeds', to='tweet.feeds'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='retwet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retwet', to='tweet.feeds'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_retweet', to=settings.AUTH_USER_MODEL),
        ),
    ]
