# Generated by Django 5.0.6 on 2024-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_feeds_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='slug',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
